name: simokerto_pintar
description: Simokerto PINTAR - Pelayanan Informasi Terpadu dan Responsif untuk warga Simokerto.
publish_to: 'none'
version: 2.1.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # HTTP & Network
  http: ^1.2.1
  socket_io_client: ^2.0.3+1
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.4
  # Notifications & Background Services
  flutter_local_notifications: ^16.3.2
  wakelock_plus: ^1.2.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.0.1
  permission_handler: ^11.3.1
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  # State Management
  flutter_riverpod: ^2.4.10
  # Storage
  shared_preferences: ^2.2.2
  # Routing
  go_router: ^13.2.0
  # UI & Typography
  google_fonts: ^6.1.0
  # Internationalization
  intl: ^0.19.0
  # Animations
  flutter_animate: ^4.5.0
  # UI Enhancement Libraries
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  card_swiper: ^3.0.1
  flutter_slidable: ^3.0.1
  cached_network_image: ^3.3.1
  glassmorphism: ^3.0.0
  lottie: ^3.3.1
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#4F46E5"
    theme_color: "#4F46E5"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/loading.json
    - assets/animations/success.json
    - assets/animations/empty.json
